SMTP_HOST: ${SMTP_HOST:-smtp.office365.com}
SMTP_PORT: ${SMTP_PORT:-587}
EMAIL_TEMPLATE_PATH: ${EMAIL_TEMPLATE_PATH:-./template/alert_email.html}
EMAIL_LOGO_PATH: ${EMAIL_LOGO_PATH:-./template/ever_logo.png}
SMTP_USERNAME: ${SMTP_USERNAME}
SMTP_PASSWORD: ${SMTP_PASSWORD}
EMAIL_FROM: ${EMAIL_FROM}
TO_ADDRESSES:
  - XXX@mail.com # Need modify
