gateway_id: "talosjeremy"
resend_dir: "./logs/resend"

cloud:
  ima_url: "http://imabox-server2.ima-ems.com"

# Scheduling
anchor_offset_sec: 0        # second offset to start each minute (recommended integer 0..59)
send_interval_sec: 60        # fixed interval (seconds; integer allowed, decimals if needed)
tick_grace_sec: 1          # grace period after tick (seconds; originally 800ms -> 0.8s)
fresh_window_sec: 2        # max delay considered “fresh” (seconds; originally 1000ms -> 1.0s)

# Transmission / Resend
attempt_count: 2
max_retry: -1                # -1 means unlimited retries
last_known_ttl_sec: 0        # disable fallback using old values (you want authenticity)

# Resend space protection
resend_quota_mb: 256
fs_free_min_mb: 512
resend_cleanup_batch: 100
resend_protect_recent_sec: 300

fail_resend_enabled: true
fail_resend_interval_sec: 120
fail_resend_batch: 3
last_post_ok_within_sec: 300
resend_start_delay_sec: 180  # 3 minute delay start (after 3 normal cycles)

resend_cleanup_enabled: false

sender:
  use_legacy: true
  use_aggregator: false
