gateway_id: "talosedgedv"
resend_dir: "./logs/resend"
cloud:
  ima_url: "http://imabox-server2.ima-ems.com"
send_interval_sec: 60
attempt_count: 2
max_retry: 3
grace_period_sec: 3 # tolerance for second-level delay

sender:
  use_legacy: true
  use_aggregator: false
