REG_RW_ON_OFF = "RW_ON_OFF"
HI_SHIFT, MD_SHIFT = 32, 16
DEFAULT_MISSING_VALUE = -1

# Explicit semantic constants
INVERTER_STATUS_OFFLINE_CODE = 9
INVERTER_OFFLINE_PROBE_KEYS = ("KWH", "VOLTAGE", "CURRENT", "KW", "HZ")
